AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'BMS Lambda Functions - BookMyShow Clone Backend Services

  '
Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    MemorySize: 512
    Environment:
      Variables:
        DATABASE_HOST:
          Ref: DatabaseHost
        DATABASE_PORT:
          Ref: DatabasePort
        DATABASE_NAME:
          Ref: DatabaseName
        DATABASE_USER:
          Ref: DatabaseUser
        DATABASE_PASSWORD:
          Ref: DatabasePassword
        DATABASE_SSL: 'true'
        REDIS_HOST:
          Ref: RedisHost
        REDIS_PORT:
          Ref: RedisPort
        REDIS_TLS: 'true'
        SQS_QUEUE_URL: https://sqs.ap-south-1.amazonaws.com/703671918077/bms-events-queue
        HOLD_TTL_SECONDS: '300'
        ORDER_TTL_SECONDS: '300'
        MAX_SEATS_PER_BOOKING: '10'
Parameters:
  DatabaseHost:
    Type: String
    Description: RDS PostgreSQL endpoint
    Default: your-rds-endpoint.amazonaws.com
  DatabasePort:
    Type: String
    Description: Database port
    Default: '5432'
  DatabaseName:
    Type: String
    Description: Database name
    Default: bms_production
  DatabaseUser:
    Type: String
    Description: Database username
    Default: bms_user
  DatabasePassword:
    Type: String
    Description: Database password
    NoEcho: true
    Default: your-secure-password
  RedisHost:
    Type: String
    Description: ElastiCache Redis endpoint
    Default: your-elasticache-endpoint.amazonaws.com
  RedisPort:
    Type: String
    Description: Redis port
    Default: '6379'
Resources:
  BMSApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: '''GET,POST,PUT,DELETE,OPTIONS'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-user-id'''
        AllowOrigin: '''*'''
    Metadata:
      SamResourceId: BMSApi
  MoviesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bms-movies-service
      CodeUri: s3://bms-lambda-deployment-1765969818/d8fe0a9ef2250ba1662418c817d3495d
      Handler: handlers.movies.lambda_handler
      Environment:
        Variables:
          REDIS_URL: redis://default:bY6nYQasYLWeBJvSUjs6VmfYxYHROp1u@redis-15866.crce182.ap-south-1-1.ec2.cloud.redislabs.com:15866
          DATABASE_URL: postgresql://postgres:2kTqQ7Mcl054kELxa955@bookmyshow.cxwyaqu60aes.ap-south-1.rds.amazonaws.com:5432/bms
          SQS_QUEUE_URL: https://sqs.ap-south-1.amazonaws.com/905418273616/bms-events-queue
          LOG_LEVEL: INFO
          HOLD_TTL_SECONDS: 300
      Policies:
      - VPCAccessPolicy: {}
      - Statement:
        - Effect: Allow
          Action:
          - rds:DescribeDBInstances
          - rds:DescribeDBClusters
          Resource: '*'
      Events:
        GetMovies:
          Type: Api
          Properties:
            RestApiId:
              Ref: BMSApi
            Path: /movies
            Method: GET
        GetMovieDetails:
          Type: Api
          Properties:
            RestApiId:
              Ref: BMSApi
            Path: /movies/{movieId}
            Method: GET
        GetMovieShows:
          Type: Api
          Properties:
            RestApiId:
              Ref: BMSApi
            Path: /movies/{movieId}/shows
            Method: GET
    Metadata:
      SamResourceId: MoviesFunction
  SeatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bms-seats-service
      CodeUri: s3://bms-lambda-deployment-1765969818/d8fe0a9ef2250ba1662418c817d3495d
      Handler: handlers.seats.lambda_handler
      Environment:
        Variables:
          REDIS_URL: redis://default:bY6nYQasYLWeBJvSUjs6VmfYxYHROp1u@redis-15866.crce182.ap-south-1-1.ec2.cloud.redislabs.com:15866
          DATABASE_URL: postgresql://postgres:2kTqQ7Mcl054kELxa955@bookmyshow.cxwyaqu60aes.ap-south-1.rds.amazonaws.com:5432/bms
          SQS_QUEUE_URL: https://sqs.ap-south-1.amazonaws.com/905418273616/bms-events-queue
          LOG_LEVEL: INFO
          HOLD_TTL_SECONDS: 300
      Policies:
      - VPCAccessPolicy: {}
      - Statement:
        - Effect: Allow
          Action:
          - rds:DescribeDBInstances
          - rds:DescribeDBClusters
          Resource: '*'
      Events:
        GetSeatMap:
          Type: Api
          Properties:
            RestApiId:
              Ref: BMSApi
            Path: /shows/{showId}/seatmap
            Method: GET
        CreateHold:
          Type: Api
          Properties:
            RestApiId:
              Ref: BMSApi
            Path: /holds
            Method: POST
        GetHold:
          Type: Api
          Properties:
            RestApiId:
              Ref: BMSApi
            Path: /holds/{holdId}
            Method: GET
        UpdateHold:
          Type: Api
          Properties:
            RestApiId:
              Ref: BMSApi
            Path: /holds/{holdId}
            Method: PUT
        ReleaseHold:
          Type: Api
          Properties:
            RestApiId:
              Ref: BMSApi
            Path: /holds/{holdId}
            Method: DELETE
    Metadata:
      SamResourceId: SeatsFunction
  OrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bms-orders-service
      CodeUri: s3://bms-lambda-deployment-1765969818/d8fe0a9ef2250ba1662418c817d3495d
      Handler: handlers.orders.lambda_handler
      Environment:
        Variables:
          REDIS_URL: redis://default:bY6nYQasYLWeBJvSUjs6VmfYxYHROp1u@redis-15866.crce182.ap-south-1-1.ec2.cloud.redislabs.com:15866
          DATABASE_URL: postgresql://postgres:2kTqQ7Mcl054kELxa955@bookmyshow.cxwyaqu60aes.ap-south-1.rds.amazonaws.com:5432/bms
          SQS_QUEUE_URL: https://sqs.ap-south-1.amazonaws.com/905418273616/bms-events-queue
          LOG_LEVEL: INFO
          HOLD_TTL_SECONDS: 300
      Policies:
      - VPCAccessPolicy: {}
      - SQSSendMessagePolicy:
          QueueName: bms-events-queue
      - Statement:
        - Effect: Allow
          Action:
          - rds:DescribeDBInstances
          - rds:DescribeDBClusters
          Resource: '*'
      Events:
        CreateOrder:
          Type: Api
          Properties:
            RestApiId:
              Ref: BMSApi
            Path: /orders
            Method: POST
        GetOrder:
          Type: Api
          Properties:
            RestApiId:
              Ref: BMSApi
            Path: /orders/{orderId}
            Method: GET
        ConfirmPayment:
          Type: Api
          Properties:
            RestApiId:
              Ref: BMSApi
            Path: /orders/{orderId}/confirm-payment
            Method: POST
    Metadata:
      SamResourceId: OrdersFunction
  EventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bms-events-processor
      CodeUri: s3://bms-lambda-deployment-1765969818/d8fe0a9ef2250ba1662418c817d3495d
      Handler: handlers.events.lambda_handler
      Environment:
        Variables:
          REDIS_URL: redis://default:bY6nYQasYLWeBJvSUjs6VmfYxYHROp1u@redis-15866.crce182.ap-south-1-1.ec2.cloud.redislabs.com:15866
          DATABASE_URL: postgresql://postgres:2kTqQ7Mcl054kELxa955@bookmyshow.cxwyaqu60aes.ap-south-1.rds.amazonaws.com:5432/bms
          SQS_QUEUE_URL: https://sqs.ap-south-1.amazonaws.com/905418273616/bms-events-queue
          LOG_LEVEL: INFO
          HOLD_TTL_SECONDS: 300
      Policies:
      - SQSPollerPolicy:
          QueueName: bms-events-queue
    Metadata:
      SamResourceId: EventsFunction
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
      - PolicyName: BMSLambdaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            Resource:
            - arn:aws:sqs:ap-south-1:703671918077:bms-events-queue
            - arn:aws:sqs:ap-south-1:703671918077:bms-notifications-queue
    Metadata:
      SamResourceId: LambdaExecutionRole
Outputs:
  BMSApiEndpoint:
    Description: API Gateway endpoint URL for BMS services
    Value:
      Fn::Sub: https://${BMSApi}.execute-api.${AWS::Region}.amazonaws.com/prod/
    Export:
      Name: BMSApiEndpoint
  BMSEventsQueueURL:
    Description: SQS Queue URL for events
    Value: https://sqs.ap-south-1.amazonaws.com/703671918077/bms-events-queue
    Export:
      Name: BMSEventsQueueURL
